name: SSLChecker Build and Test

on:
  push:
    branches: [ main ]
    paths:
      - 'SSLChecker/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'SSLChecker/**'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore
      run: dotnet restore
      working-directory: SSLChecker
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: SSLChecker
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: SSLChecker
